stages:
  - deploy
  - rollback

.deploy_template: &ssh_template
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh bash docker-cli
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

deploy_production:
  stage: deploy
  <<: *ssh_template
  script:
    - echo ">>> SSH vào server và deploy"
    - |
      ssh "$DEPLOY_USER@$DEPLOY_HOST" <<EOF
        echo ">>> Pull image mới nhất từ Docker Hub"
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        docker pull $IMAGE_NAME:latest
        echo ">>> Deploy bằng docker-compose"
        docker compose -f /home/$DEPLOY_USER/docker-compose.yml up -d --force-recreate
      EOF

rollback:
  stage: rollback
  when: manual
  allow_failure: true
  <<: *ssh_template
  script:
    - echo ">>> SSH vào server và rollback"
    - |
      ssh "$DEPLOY_USER@$DEPLOY_HOST" <<EOF
        echo ">>> Pull image rollback từ Docker Hub"
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        docker pull $IMAGE_NAME:rollback
        echo ">>> Rollback bằng docker-compose"
        docker compose -f /home/$DEPLOY_USER/docker-compose.rollback.yml up -d --force-recreate
      EOF
