stages:
  - deploy
  - rollback

deploy_production:
  stage: deploy
  only:
    - main
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
  script:
    - echo "🔐 Logging into $DEPLOY_USER@$DEPLOY_HOST"
    - |
      ssh "$DEPLOY_USER@$DEPLOY_HOST" << 'EOF'
        echo "🛑 Stopping old container (if any)"
        docker stop app || true
        docker rm app || true
        echo "📥 Pulling latest image from Docker Hub"
        docker pull $IMAGE_NAME:latest
        echo "🚀 Running new container"
        docker run -d --name app -p 5000:5000 $IMAGE_NAME:latest
      EOF

rollback:
  stage: rollback
  image: alpine:latest
  when: manual
  allow_failure: true
  before_script:
    - apk add --no-cache openssh-client docker-cli
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
  script:
    - echo "🔐 SSHing to server for rollback"
    - |
      ssh "$DEPLOY_USER@$DEPLOY_HOST" << 'EOF'
        echo "🛑 Stopping current container"
        docker stop app || true
        docker rm app || true
        echo "📥 Pulling rollback image from Docker Hub"
        docker pull $IMAGE_NAME:rollback
        echo "🚀 Running rollback container"
        docker run -d --name app -p 5000:5000 $IMAGE_NAME:rollback
      EOF