stages:
  - deploy
  - rollback

deploy_production:
  stage: deploy
  only:
    - main
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
  script:
    - echo "🔐 Đăng nhập  $DEPLOY_USER@$DEPLOY_HOST"
    - |
      ssh "$DEPLOY_USER@$DEPLOY_HOST" << 'EOF'
        echo "🛑 Dừng container cũ (nếu có)"
        docker stop app || true
        docker rm app || true

        echo "📥 Pull image mới từ Docker Hub"
        docker pull $IMAGE_NAME:latest

        echo "🚀 Chạy container mới"
        docker run -d --name app -p 5000:5000 $IMAGE_NAME:latest
      EOF

rollback:
  stage: rollback
  image: alpine:latest
  when: manual
  allow_failure: true
  before_script:
    - apk add --no-cache openssh docker-cli
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
  script:
    - echo "🔐 SSH vào server để rollback"
    - |
      ssh "$DEPLOY_USER@$DEPLOY_HOST" << EOF
        echo "🛑 Dừng container hiện tại"
        docker stop app || true
        docker rm app || true

        echo "📥 Pull image rollback từ Docker Hub"
        docker pull $IMAGE_NAME:rollback

        echo "🚀 Chạy container rollback"
        docker run -d --name app -p 5000:5000 $IMAGE_NAME:rollback
      EOF
